### ISSUE TITLE
إقتراح: إضافة قاموس أبل

### ISSUE THREAD

**Issue by Ali-x98** [Abdelaziz18003/mostalah#2]
السلام عليكم ورحمة الله وبركاته.

كنت أتصفح دليل ترجمة اللغة العربية لموزيلا، ووجدت أنهم يوصون باستخدام قاموسي مايكروسوفت وأبل، وقاموس مايكروسوفت موجود بالفعل في مصطلح، لذلك أود أن اقترح إضافة قاموس أبل كذلك.

[صفحة دليل الترجمة العربية لموزيلا](https://mozilla-l10n.github.io/styleguides/ar/).

[رابط قاموس أبل](https://developer.apple.com/download/more/?=Glossaries).

وشكرًا.

**Comment by Abdelaziz18003** [comment]
نعم اقتراح رائع، سأعمل على إضافتها في الأيام المقبلة بإذن الله
